### ISSUE TITLE
Disable enterprise repo instead of removing it

### ISSUE THREAD

**Issue by SebDanielsson** [simoncaron/ansible-role-pve_addons#2]
Hi!

I would like to disable the enterprise repo instead of removing it. That way it can easily be restored.

I currently use this task to do it:

```yaml
- name: Ensure enterprise repo is not enabled
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: "^deb "
    replace: '# \g<0>'
  notify: Refresh package cache
```

What do you think?😊
